### ISSUE TITLE
[Question] What is "Free Image Size" ? 

### ISSUE THREAD

**Issue by gachiemchiep** [ShuangXieIrene/ssds.pytorch#28]
Hello @ShuangXieIrene and @foreverYoungGitHub  .

Thank you for your great contribution.

As the title said, what is "Free Image Size" ? 

In the .cfg file, there are several settings as below. If i want to change the IMAGE_SIZE: [300, 300] to IMAGE_SIZE: [512, 512], then do i have to change the other parameters as well ? If that's so, how can i change those ?

```
MODEL:
  SSDS: ssd
  NETS: resnet_50
  IMAGE_SIZE: [300, 300]
  NUM_CLASSES: 21
  FEATURE_LAYER: [[10, 16, 'S', 'S', '', ''], [512, 1024, 512, 256, 256, 256]]
  STEPS: [[8, 8], [16, 16], [32, 32], [64, 64], [100, 100], [300, 300]]
  SIZES: [[30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
  ASPECT_RATIOS: [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2], [1, 2]]
```

Thank you for your time
